# Step 0: run with frozen VGG16 encoders (for first 10 epochs)
model_name_suffix:
  - "seg"
  - "b1"
slurm:
  partition: "gpu"
  gres: "gpu:titanrtx:1"
  cpus_per_task: 4
  memory_gb: 8
  approx_ms_per_epoch_step: 525
settings:
  model: "vgg16_unet"
  output_channels: 1
  output_activation: "sigmoid"
  padding: "same"
  resize_output: False
  resize_use_batch_norm: False
  vgg16_use_imagenet_weights: True
  vgg16_freeze_encoders: True
  vgg16_conv_activation: "relu"
  unet_use_batch_norm: False
  unet_use_attention_gate: False
  unet_upsampling: "odena_2016"
  unet_conv_activation: "elu"
  annotation_keys:
    - "segmentation-mask"
    - "segmentation-boundary-weights"
  transformers:
    - name: "fix_segmentation_weights"
  loss:
    name: "tversky"
