model_name_suffix:
  - loss
  - a1
settings:
  loss:
    segmentation_map:
      name: Tversky
      parameters:
        alpha: 0.6
        weights_index: null
    cover:
      name: MeanSquaredError
  loss_weights:
    segmentation_map: 1.0
    cover: 0.25
