title: "Density ground truths using cross-validation"
ref: tab:exp-gt-cv
datasets:
  2: Sahel-Sudan
static_columns:
  supervision: Supervision
  split: Split
  seed: Seed
models:
  - folder: density2-d1-scaled-loss-a1-u1-adam2-cv-0-sahel-207146141
    dataset: 2
    label: Uniform
    static_columns:
      supervision: Per-pixel
      split: 0
      seed: 207146141
  - folder: density2-d1-scaled-loss-a1-u1-adam2-cv-1-sahel-175229620
    dataset: 2
    label: Uniform
    static_columns:
      supervision: Per-pixel
      split: 1
      seed: 175229620
  - folder: density2-d1-scaled-loss-a1-u1-adam2-cv-2-sahel-244591021
    dataset: 2
    label: Uniform
    static_columns:
      supervision: Per-pixel
      split: 2
      seed: 244591021

  - folder: density2-d1-scaled-loss-a1-edt1-adam2-cv-0-sahel-207146141
    dataset: 2
    label: EDT
    static_columns:
      supervision: Per-pixel
      split: 0
      seed: 207146141
  - folder: density2-d1-scaled-loss-a1-edt1-adam2-cv-1-sahel-175229620
    dataset: 2
    label: EDT
    static_columns:
      supervision: Per-pixel
      split: 1
      seed: 175229620
  - folder: density2-d1-scaled-loss-a1-edt1-adam2-cv-2-sahel-244591021
    dataset: 2
    label: EDT
    static_columns:
      supervision: Per-pixel
      split: 2
      seed: 244591021

  - folder: density2-d1-scaled-loss-a1-g7-adam2-cv-0-sahel-207146141
    dataset: 2
    label: Gaussian filter on segmentation mask
    static_columns:
      supervision: Per-pixel
      split: 0
      seed: 207146141
  - folder: density2-d1-scaled-loss-a1-g7-adam2-cv-1-sahel-175229620
    dataset: 2
    label: Gaussian filter on segmentation mask
    static_columns:
      supervision: Per-pixel
      split: 1
      seed: 175229620
  - folder: density2-d1-scaled-loss-a1-g7-adam2-cv-2-sahel-244591021
    dataset: 2
    label: Gaussian filter on segmentation mask
    static_columns:
      supervision: Per-pixel
      split: 2
      seed: 244591021

  - folder: density2-d1-scaled-loss-a1-g3-adam2-cv-0-sahel-207146141
    dataset: 2
    label: Energy centroid
    static_columns:
      supervision: Point
      split: 0
      seed: 207146141
  - folder: density2-d1-scaled-loss-a1-g3-adam2-cv-1-sahel-175229620
    dataset: 2
    label: Energy centroid
    static_columns:
      supervision: Point
      split: 1
      seed: 175229620
  - folder: density2-d1-scaled-loss-a1-g3-adam2-cv-2-sahel-244591021
    dataset: 2
    label: Energy centroid
    static_columns:
      supervision: Point
      split: 2
      seed: 244591021

  - folder: density2-d1-scaled-loss-a1-g4-adam2-cv-0-sahel-207146141
    dataset: 2
    label: Standard centroid
    static_columns:
      supervision: Point
      split: 0
      seed: 207146141
  - folder: density2-d1-scaled-loss-a1-g4-adam2-cv-1-sahel-175229620
    dataset: 2
    label: Standard centroid
    static_columns:
      supervision: Point
      split: 1
      seed: 175229620
  - folder: density2-d1-scaled-loss-a1-g4-adam2-cv-2-sahel-244591021
    dataset: 2
    label: Standard centroid
    static_columns:
      supervision: Point
      split: 2
      seed: 244591021

columns:
  - key: val_count_r_square
    label: Count R2
    best: max
  - key: val_count_rmse
    label: Count RMSE
    best: min
  - key: val_count_mae
    label: Count MAE
    best: min
  - key: val_density_map_r_square
    label: DM R2
    best: max
  - key: val_density_map_rmse
    label: DM RMSE
    best: min
  - key: val_density_map_mae
    label: DM MAE
    best: min
