model_name_suffix:
  - adam
  - cyc
settings:
  optimizer:
    name: Adam
    parameters:
      learning_rate:
        name: TriangularCyclicalLearningRate
        parameters:
          initial_learning_rate: !!float "1e-3"
          maximal_learning_rate: !!float "1e-2"
          step_size: 960
          scale_mode: cycle
      epsilon: !!float "1e-9"
