model_name_suffix:
  - sgd
  - cyc
  - high
settings:
  optimizer:
    name: SGD
    parameters:
      momentum: 0.0
      learning_rate:
        name: TriangularCyclicalLearningRate
        parameters:
          initial_learning_rate: !!float "1e-6"
          maximal_learning_rate: !!float "0.1"
          step_size: !!int "960"
          scale_mode: cycle
