model_name_suffix:
  - sgd
  - cyc
settings:
  optimizer:
    name: SGD
    parameters:
      momentum: 0.0
      learning_rate:
        name: TriangularCyclicalLearningRate
        parameters:
          initial_learning_rate: !!float "3e-4"
          maximal_learning_rate: !!float "1e-3"
          step_size: !!int "960"
          scale_mode: cycle
