model_name_suffix:
  - seg
  - attention
  - a
slurm:
  partition: "gpu"
  gres: "gpu:titanrtx:1"
  cpus_per_task: 4
  memory_gb: 8
  approx_ms_per_epoch_step: 400
settings:
  annotation_keys:
    - "segmentation-mask"
    - "segmentation-boundary-weights"
    - "outlier-weights"
  loader_patch_defaults: !!python/tuple [[[0.0, 0.0]], [0.0, 0.0, -1.0]]
  transformers:
    - name: "fix_boundary_and_outlier_weights"
  model: "unet"
  output_channels: 1
  output_activation: "sigmoid"
  padding: "same"
  depth: 4
  layer_count: 64
  output_resize_interpolation: null
  conv_activation: "relu"
  encoder_unit: "vanilla"
  encoder_pooling: "max"
  decoder_unit: "vanilla"
  decoder_upsampling: "vanilla"
  decoder_upsampling_use_batch_norm: False
  decoder_use_attention_gate: True
