model_name_suffix:
  - "seg"
  - "sdunet"
slurm:
  partition: "gpu"
  gres: "gpu:titanrtx:1"
  cpus_per_task: 4
  memory_gb: 8
  approx_ms_per_epoch_step: 700
settings:
  annotation_keys:
    - "segmentation-mask"
    - "segmentation-boundary-weights"
  transformers:
    - name: "fix_segmentation_weights"
  loss:
    name: "tversky"
  model: "unet"
  output_channels: 1
  output_activation: "sigmoid"
  padding: "same"
  depth: 4
  layer_count: 64
  output_resize_interpolation: null
  output_resize_use_batch_norm: False
  conv_activation: "elu"
  encoder_unit: "sdunet"
  encoder_pooling: "max"
  decoder_unit: "sdunet"
  decoder_upsampling: "odena_2016"
  decoder_upsampling_use_batch_norm: False
  decoder_use_attention_gate: False
