model_name_suffix:
  - loss
  - a1
  - h256
settings:
  loss:
    density_map:
      name: MSEPlusHistogram
      parameters:
        k: 256
        start: -5.0
        stop: 20.0
        alpha1: 1.0
        alpha2: 0.25
    count: null
    cover: null
  loss_weights:
    density_map: 1.0
    count: 0.0
    cover: 0.0
